# Generated by Django 2.2.7 on 2019-11-16 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=10, null=True, unique=True, verbose_name='称号')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('uid', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='用户ID')),
                ('job', models.CharField(max_length=10, unique=True, verbose_name='用户工号')),
                ('username', models.CharField(max_length=10, null=True, verbose_name='用户名')),
                ('image', models.CharField(max_length=10, null=True, verbose_name='图片地址')),
                ('password', models.CharField(max_length=64, null=True, verbose_name='密码')),
                ('email', models.CharField(max_length=20, null=True, verbose_name='邮箱')),
            ],
        ),
        migrations.CreateModel(
            name='UserAndTitle',
            fields=[
                ('id', models.IntegerField(auto_created=True, db_index=True, primary_key=True, serialize=False)),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webApp.Title', to_field='profession', verbose_name='职称')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webApp.UserInfo', to_field='job', verbose_name='用户')),
            ],
        ),
        migrations.CreateModel(
            name='DateAndWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateTimeField(null=True, verbose_name='签到时间')),
                ('endtime', models.DateTimeField(null=True, verbose_name='签退时间')),
                ('status', models.CharField(default='未签到', max_length=20, verbose_name='状态')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webApp.UserInfo', to_field='job')),
            ],
        ),
    ]
