# Generated by Django 3.0.6 on 2020-06-14 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dateandweek',
            options={'verbose_name': '时间记录表'},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'verbose_name': '职称表'},
        ),
        migrations.AlterModelOptions(
            name='userandtitle',
            options={'verbose_name': '用户职称关联表'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': '用户表'},
        ),
        migrations.AddField(
            model_name='userinfo',
            name='image_content',
            field=models.TextField(null=True, verbose_name='图片信息'),
        ),
    ]
